print("Hello welcome to git account!!!!")
print("Welcome to this account!!!!!")
print("This is Aishwarya Molankal!!!")
a=int(input("Enter number a:"))
b=int(input("Enter number b:"))
print("Add is:",a+b)
print("Added lines throgh git hub account")
print("edited by umesh")
print("HAHAHAHAAH")
